<?php

/**
 * @var \Hiberus\Bitrian\Block\Index $block
 */
$alumnos = $block->getAlumno();
$notas = $block->getAverageMarks();
$notaMinima = $block->getNota();
$i = 0;
$elementos = $block->getElementos();
$maxMarks = $block->getMaxMarks();
?>
<button id="btnDisplay">Mostrar/ocultar lista de alumnos</button>
<button id="notaMasAlta">Ver nota mas alta</button>
<h2 class="title">Alumnos</h2>
<div id="alumnos">
    <?php
        foreach($alumnos as $alumno) {
            if ($i++ == $elementos) break;

            if($alumno->getMark() > $notaMinima){

                $classEvaluation = "approved";
            }else{
                $classEvaluation = "suspensed";
            }

    ?>

    <ul>
        <li>Nombre:<?= $alumno->getFirstName(); ?></li>
         <li>Apellido: <?= $alumno->getLastName(); ?></li>
        <li class="<?=$classEvaluation?>">Nota:<?= $alumno->getMark(); ?></li>
    </ul>

    <?php } ?>
</div>

Notas mas altas:
<?php foreach($maxMarks as $mark) { ?>
    <p><?= $mark ?></p>
<?php } ?>
<p> Media de notas: <?=$notas?> </p>

<p> Total de alumnos: <?= (count($alumnos)) ?> </p>

<script>
    var maxNote = <?= $block->getMaxMark() ?>
</script>

<script>
    require(['jquery', 'btndisplay'], function($, btndisplay) {
        btndisplay('#btnDisplay','#alumnos');
    });

    require(['jquery', 'alertNotaAlta'], function($, alertNotaAlta) {
        alertNotaAlta('#notaMasAlta');
    });
</script>


